### ISSUE TITLE
Multisite reverts only revert the site that broke

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/deployments#200]
If you have a multisite architecture and one of the sites breaks, the script will stop and revert the database and settings for _the site that failed_ but not any others it previously built in the process.

We'll need to somehow build a list of already 'treated' sites in a build and go back and revert each one in turn in the event of a failure further down the line.

Also, when drush updates fail for multisites it does not revert the link to the previous build directory.

So there are a few logical flaws to overcome for rolling back multisite builds. Should probably be tackled as a single refactoring job of revert behaviour to make it handle multisites and associated generic links.

**Comment by EmlynK** [comment]
> Also, when drush updates fail for multisites it does not revert the link to the previous build directory.

The same applies to feature reverts during D7 builds.

Perhaps we ought to work out a way to pull out the live symlink from the `for` loop, so it only happens once every site has been deployed? Or it happens at the start, before the loop. Either way, the live symlink adjust would only happen once, rather than for every site in the project.

**Comment by EmlynK** [comment]
This has been fixed. See the following commits:
* 0bc82180cd1c88c66d7a4672f9de09032274d68e
* c5e319363727f332b04ac863e494cb04c52c91b5
* 6da29a0abf93784374ef5f45861c03c0821a1be5

Closing issue.
